name: build

env:
  DOCKER_IMAGE: ghcr.io/himitery/eas-slack-bot

on:
  push:
    branches:
      - main


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 1. set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.5

      - name: 2. set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.7.0

      - name: 3. set up docker layer caches
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.version }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: 4. login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: himitery
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 5. docker build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest